// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdYRUUYYMurGoE7XgjFQvA71YsZQE8j3o',
    appId: '1:838600922546:android:ddb2033234fe538e8840ab',
    messagingSenderId: '838600922546',
    projectId: 'where-6c138',
    storageBucket: 'where-6c138.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIAEWh2oL0hloAMyboLnyDCCtX-YXns1c',
    appId: '1:838600922546:ios:04f057aa26d617b18840ab',
    messagingSenderId: '838600922546',
    projectId: 'where-6c138',
    storageBucket: 'where-6c138.appspot.com',
    androidClientId: '838600922546-sliudb4ru288qctq7h2upj69cqrm7uaf.apps.googleusercontent.com',
    iosClientId: '838600922546-uchlu00ok198lukf1a0apsa2pokfrqjl.apps.googleusercontent.com',
    iosBundleId: 'com.junjieyang.where',
  );
}
